### ISSUE TITLE
Smooth Shading?

### ISSUE THREAD

**Issue by zauberparacelsus** [NewDavidg0/Smooth-Infinite-Voxel-Terrain#1]
I noticed from the screenshots that the generated terrain has flat shading.  Any plans to implement smooth shading?  Outside of that one issue, this engine seems to be just perfect for a planned project.

**Comment by DXGatech** [comment]
Hey Zauber
Don't worry, we support smooth shading for our project. 
The lowpoly effect is intentionally created by the terrain material, which is processed with DDX and DDY nodes. More information about lowpoly material: https://answers.unrealengine.com/questions/499170/ddxddy-on-android-for-flat-shading.html
The reason why we use this asset is mainly because of my personal taste and a lack of art assets. We plan to make a presentation video with realistic terrain materials later on.
Thanks for reminding! I'll add this to the readme file later in case other people have similar questions.
I'll leave this open for several hours so that you can feel free to ask more :)
